# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe14e1b702dc4093cced96eb5a82719a0d1192177e1abb79cadca0f83f9398dfeebf1a9b650b04b22e4f332693f932b9e6599d2530944b806d8c3fef19ed8950

test:
  secret_key_base: 13273bfbe1e905b46244b19168ea39254187e2fb485ef95a3a92c01250e42d3efb12e0dbdefc9b94e49c107ca2aa590de45cd76db8b9f14a325428ad12d972bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
